apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    isDefault: false
    database: "otel-traces" # ou otel-logs, otel-metrics — depende do index
    jsonData:
      timeField: "@timestamp"
      esVersion: 8
      logMessageField: "message"
