{
 "title": "dashboardXPTO2",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Disk I/O - Throughput",
   "type": "stat",
   "description": "shows how much data (in bytes) is being written to disk per second, averaged over the last 1 minute.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, rate(system_disk_io_bytes_total{direction=\"write\", device!~\"loop.*\"}[1m]))\r\n\r\n\r\n\r\n",
     "legendFormat": "{{device}} - {{direction}}"
    }
   ]
  },
  {
   "title": "Rate of disk I/O operations",
   "type": "stat",
   "description": "Rate of disk I/O operations per second over the past 1 minute.",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(system_disk_operations_total{device!~\"loop.*\"}[1m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "description": "Used to measure the network throughput over the past 1 minute, aggregated by each network interface.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(system_network_io_bytes_total[1m])",
     "legendFormat": "{{device}} - {{direction}} - Network Throughput (B/s)"
    }
   ]
  },
  {
   "title": "Network - Error Rate",
   "type": "timeseries",
   "description": "Measures the rate of network errors per second, averaged over the last minute.",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(system_network_errors_total[1m])\r\n",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}