{
 "title": "dashboardXPTO3",
 "description": "dashboardXPTO3",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requests per Minute",
   "type": "gauge",
   "description": "Requests per Minute.",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Endpoints",
   "type": "barchart",
   "description": "Top Endpoints.",
   "gridPos": { "h": 8, "w": 11, "x": 5, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "attributes.http.route.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "1", "size": "3" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU cores",
   "type": "timeseries",
   "description": "Number of CPU cores",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "count(count by (cpu) (system_cpu_time_seconds_total))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Methods Distribution",
   "type": "barchart",
   "description": "HTTP Methods Distribution.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "attributes.http.method.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Status Code Breakdown",
   "type": "stat",
   "description": "Status Code Breakdown.",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "attributes.http.status_code",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "* AND attributes.http.status_code:[100 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU demand",
   "type": "timeseries",
   "description": "This is the 1-minute load average.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    { "expr": "system_cpu_load_average_1m", "legendFormat": "__auto" }
   ]
  }
 ]
}