{
 "title": "metricsDash",
 "description": "metricsDash",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Show if targets are up.",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"otel-collector:8890\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "stat",
   "description": "CPU Load (1m / 5m / 15m)",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_cpu_load_average_1m", "legendFormat": "1m" },
    { "expr": "system_cpu_load_average_5m", "legendFormat": "5m" },
    { "expr": "system_cpu_load_average_15m", "legendFormat": "15m" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "memory usage percentage.",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(system_memory_usage_bytes{state=\"used\", instance=\"otel-collector:8890\"}) \r\n  / \r\n  (sum(system_memory_usage_bytes{state=\"used\", instance=\"otel-collector:8890\"}) \r\n   + sum(system_memory_usage_bytes{state=\"free\", instance=\"otel-collector:8890\"}))) * 100\r\n\r\n",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Total HTTP Requests [1m]",
   "type": "stat",
   "description": "Total number of HTTP requests observed over the past 1 minute.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(http_server_request_count_total[1m])\r\n",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Latency 95th",
   "type": "barchart",
   "description": "95th percentile latency.",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_milliseconds_bucket[1m])) by (le))\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}