{
 "title": "xyzDash",
 "description": "xyzDash  Dash",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Top 3 Endpoints",
   "type": "piechart",
   "description": "Top 3 Endpoints",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "attributes.http.route.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "3" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Trace Insight Table",
   "type": "table",
   "description": "Dashboard",
   "gridPos": { "h": 9, "w": 18, "x": 5, "y": 0 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top 1 Service - Request Count",
   "type": "barchart",
   "description": "Top 1 Service",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "resource.attributes.service.name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top 1 Corporation - Request Count",
   "type": "barchart",
   "description": "Top-performing Corp (by request count) ",
   "gridPos": { "h": 8, "w": 14, "x": 9, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "resource.attributes.organization.name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "description": "Shows total CPU usage per instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(system_cpu_time_seconds_total{state=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage % per instance",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\r\n  sum by(instance) (system_memory_usage_bytes{state=\"used\"})\r\n  /\r\n  sum by(instance) (system_memory_usage_bytes)\r\n)\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}