receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      memory:
      disk:
      filesystem:
      load:
      network:
      paging:
      processes:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8890"
  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]
    tls:
      insecure: true
    traces_index: "otel-traces"
    logs_index: "otel-logs"
  debug: {}

service:
  pipelines:
    metrics:
      receivers: [otlp , hostmetrics]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      exporters: [elasticsearch, debug]
    logs:
      receivers: [otlp]
      exporters: [elasticsearch, debug]
